CREATE DATABASE IF NOT EXISTS memoryos;
USE memoryos;

CREATE TABLE IF NOT EXISTS images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner_id VARCHAR(128) NOT NULL DEFAULT 'local-user',
  filename VARCHAR(512) NOT NULL,
  file_path VARCHAR(1024) NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  image_width INT UNSIGNED NULL,
  image_height INT UNSIGNED NULL,
  file_hash CHAR(64) NULL,
  phash CHAR(16) NULL,
  file_modified_at DATETIME NULL,
  mime_type VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  subcategory VARCHAR(128) NULL,
  location VARCHAR(512) NULL,
  importance ENUM('Critical', 'Important', 'Normal', 'Low') NOT NULL DEFAULT 'Normal',
  ocr_text MEDIUMTEXT NULL,
  ocr_confidence DECIMAL(5,4) NULL,
  ocr_status ENUM('pending', 'complete', 'failed') NOT NULL DEFAULT 'pending',
  visual_description TEXT NULL,
  keywords TEXT NULL,
  image_embedding MEDIUMBLOB NULL,
  image_data LONGBLOB NULL,
  confidence DECIMAL(5,4) NULL,
  classification_candidates JSON NULL,
  classification_evidence JSON NULL,
  classification_margin DECIMAL(8,6) NULL,
  importance_score TINYINT UNSIGNED NOT NULL DEFAULT 50,
  protection_status ENUM('unprotected', 'protected') NOT NULL DEFAULT 'unprotected',
  processing_status ENUM('pending', 'processing', 'completed', 'failed', 'needs_review') NOT NULL DEFAULT 'completed',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_images_owner (owner_id),
  INDEX idx_images_category (category),
  INDEX idx_images_subcategory (subcategory),
  INDEX idx_images_importance (importance),
  INDEX idx_images_created (created_at),
  INDEX idx_images_mime_type (mime_type),
  INDEX idx_images_location (location),
  INDEX idx_images_filename (filename),
  INDEX idx_images_owner_hash (owner_id, file_hash),
  INDEX idx_images_phash (phash),
  INDEX idx_images_path (file_path),
  INDEX idx_images_processing (processing_status),
  INDEX idx_images_protection (protection_status),
  FULLTEXT INDEX ft_images_search (filename, ocr_text, visual_description, keywords, category, subcategory, location)
);
